name: Build ViveToolGui EXE

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.402'

      - name: Restore dependencies
        run: dotnet restore ViveToolGui/ViveToolGui.csproj

      - name: Build and Publish EXE
        run: |
          dotnet publish ViveToolGui/ViveToolGui.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=false -p:WindowsPackageType=None -o ./publish

      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ViveToolGui-EXE
          path: ./publish/*
